//
//  ContentView.swift
//  CodingChallenge1
//
//  Created by Scott Bennett on 5/29/21.
//

import SwiftUI

enum cell: String {
    case L = "L"
    case D = "."
    case A = "#"
}

struct ContentView: View {
    
    
    @State private var cultures = [
        [cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,],
        [cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,],
        [cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,],
        [cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,],
        [cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.L,cell.D,cell.D,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.D,cell.D,cell.L,cell.L,cell.D,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.D,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,],
        [cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.D,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,cell.L,]

        
    ]
    
    @State private var tempArray: [[cell]] = [[]]
    @State private var isChanged: Bool = false
    @State private var hours: Int = 0
    @State private var liveCultures: Int = 0
    @State private var liveRatio: Double = 0
    @State private var switchTest: Bool = true
    
    var iterations = 0
    
    var body: some View {
        VStack {
            Text("Cultures")
            
            VStack {
                ForEach(cultures, id: \.self) { array in
                    HStack {
                        ForEach(array, id: \.self) { element in
                            Text(element.rawValue)
                                .font(.system(.body, design: .monospaced))
                        }
                    }
                }
            }
            
            Button(action: {
                activate()
                isChanged = true
            }, label: {
                Text("Activate")
            })
            .padding()
            
            Button(action: {
                for _ in 1... {
                    if !isChanged { break }
                    isChanged = false
                    performTest()
                }
                answers()
                
            }, label: {
                Text("Continue")
            })
            .disabled(!isChanged)
            .padding()
            
            Text("Hours: \(hours)")
            Text("Live Cultures: \(liveCultures)")
            Text("Live/Livable Spaces: \(liveRatio, specifier: "%.2f")%")
            
        }
    }
    
    
    func performTest() {
            if switchTest {
                crowdingTest()
            } else {
                adjacentTest()
            }
            switchTest.toggle()
            
            if isChanged {
                hours += 1
            }
        
    }
    
    
    func activate() {
        for i in 0..<cultures.count {
            for j in 0..<cultures[0].count {
                if cultures[i][j] == cell.L {
                    cultures[i][j] = cell.A
                    hours = 1
                }
            }
        }
    }
    
    
    func crowdingTest() {
        
        tempArray = cultures
        
        for i in 0..<cultures.count {
            for j in 0..<cultures[0].count {
                if cultures[i][j] == cell.D { continue }
                
                if checkCount(i: i, j: j) >= 4 && tempArray[i][j] != cell.L {
                    tempArray[i][j] = cell.L
                    isChanged = true
                }
            }
        }
        
        cultures = tempArray
    }
    
    
    func adjacentTest() {
        
        tempArray = cultures
        
        for i in 0..<cultures.count {
            for j in 0..<cultures[0].count {
                if cultures[i][j] == cell.D { continue }
                
                if checkCount(i: i, j: j) == 0 && tempArray[i][j] != cell.A {
                    tempArray[i][j] = cell.A
                    isChanged = true
                }
            }
        }
        
        cultures = tempArray
    }
    
    
    func checkCount(i: Int, j: Int) -> Int {
        
        var testArray: [cell] = []
        
        testArray.append(i == 0 || j == 0 ? cell.D : cultures[i - 1][j - 1])
        testArray.append(j == 0 ? cell.D : cultures[i][j - 1])
        testArray.append(i == (cultures.count - 1) || j == 0 ? cell.D : cultures[i + 1][j - 1])
        testArray.append(i == 0 ? cell.D : cultures[i - 1][j])
        testArray.append(i == (cultures.count - 1) ? cell.D : cultures[i + 1]   [j])
        testArray.append(i == 0 || j == (cultures[0].count - 1) ? cell.D : cultures[i - 1][j + 1])
        testArray.append(j == (cultures[0].count - 1) ? cell.D : cultures[i][j + 1])
        testArray.append(i == (cultures.count - 1) || j == (cultures[0].count - 1) ? cell.D : cultures[i + 1][j + 1])
        
        return testArray.filter{ $0 == cell.A }.count
    }
    
    
    func answers() {
        
        var livableArray: [cell] = []
        
        for i in 0..<cultures.count {
            for j in 0..<cultures[0].count {
                if cultures[i][j] == cell.L || cultures[i][j] == cell.A {
                    livableArray.append(cultures[i][j])
                }
            }
        }
        liveCultures = livableArray.filter{ $0 == cell.L }.count
        liveRatio = (Double(liveCultures) / Double(livableArray.count)) * 100
    }
}


struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
